name: Auto-commit regenerated DOCX

on:
  push:
    branches:
      - main
    paths:
      - "docs/modules.md"
  workflow_dispatch: {}

jobs:
  regenerate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install python-docx

      - name: Generate and edit DOCX
        run: |
          python tools/python-docx-sample/md_to_level5_numbered_docx_updated.py
          cp docs/modules-outline-numbered-level5-updated-new.docx docs/modules.docx
          python tools/python-docx-sample/edit_docx.py

      - name: Commit regenerated docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/modules.docx docs/modules-edited.docx || true
          git diff --staged --quiet || (git commit -m "Regenerate modules docx [skip ci]"; git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
