name: Auto-commit regenerated docs (PAT)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"

permissions:
  contents: write

concurrency:
  group: auto-commit-docx-pat-${{ github.ref }}
  cancel-in-progress: true

jobs:
  regenerate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-docx

      - name: Generate and edit DOCX
        run: |
          python tools/python-docx-sample/md_to_level5_numbered_docx_updated.py
          cp docs/modules-outline-numbered-level5-updated-new.docx docs/modules.docx
          python tools/python-docx-sample/edit_docx.py

      - name: Commit regenerated docs
        env:
          DOCS_BOT_TOKEN: ${{ secrets.DOCS_BOT_TOKEN }}
        run: |
          git config user.name "docs-bot"
          git config user.email "docs-bot@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${DOCS_BOT_TOKEN}@github.com/${{ github.repository }}.git
          git add docs/modules.docx
          git commit -m "chore(docs): regenerate modules.docx [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
