name: Check PR Migrations

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  issues: write

jobs:
  check-migration-suffixes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install deps
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PR migration suffix check
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # comma-separated whitelist of migration suffixes that are allowed to duplicate
          MIGRATION_SUFFIX_WHITELIST: add_soft_deletes_to_users_table
          # CI harness should only run in explicit testing contexts. When triggered by a real PR
          # this workflow will pass the actual PR files; the script will detect real PRs via
          # GITHUB_EVENT_PATH and will skip any harness simulation.
        run: php ./scripts/check-pr-migration-suffixes.php
