name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      APP_ENV: testing
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite
      MAIL_MAILER: array
      CACHE_DRIVER: array
      SESSION_DRIVER: array
      QUEUE_CONNECTION: sync
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, fileinfo, intl, curl, sqlite3, pdo_sqlite
          tools: composer
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '20.19.0'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Prepare app env
        run: |
          cp .env.example .env || true
          mkdir -p database
          php -r "file_put_contents('database/database.sqlite','');"
          php artisan key:generate --ansi
          php artisan config:clear

      - name: Run Pint
        run: vendor/bin/pint -v

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon.dist --no-progress --memory-limit=1G

      - name: Run tests
        run: php artisan test --colors=always
