name: Docs Lint

on:
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - ".markdownlint.jsonc"
      - "package.json"
      - "package-lock.json"
  pull_request:
    branches: [main]
    paths:
      - "**/*.md"
      - ".markdownlint.jsonc"
      - "package.json"
      - "package-lock.json"

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i --no-audit --no-fund
          fi

      - name: Run markdownlint
        run: npx --yes markdownlint-cli "**/*.md" -c .markdownlint.jsonc --ignore node_modules --ignore vendor
