name: PR Preview DOCX

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/python-docx-sample/requirements.txt
      - name: Run converter
        run: |
          python tools/python-docx-sample/edit_docx.py
      - name: Upload generated docs
        uses: actions/upload-artifact@v4
        with:
          name: pr-generated-docs
          path: |
            docs/modules.docx
            docs/modules-edited.docx
