name: Scheduled Regenerate DOCX

on:
  schedule:
    - cron: '0 6 * * 1' # every Monday at 06:00 UTC
  workflow_dispatch: {}

jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/python-docx-sample/requirements.txt
      - name: Run converter
        run: |
          python tools/python-docx-sample/edit_docx.py
      - name: Upload generated docs
        uses: actions/upload-artifact@v4
        with:
          name: generated-docs-scheduled
          path: |
            docs/modules.docx
            docs/modules-edited.docx
